name: Publish package

on:
  push:
    tags: ["*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@66df2de139d7a77a89644f67a88c803d4a8cf67e
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  # TODO: comment this out for now since we publish the crate manually
  # crates:
  #   uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
  #   secrets:
  #     CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}

  # TODO: uncomment when it works
  # pypi:
  #   uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
  #   secrets:
  #     PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
